FROM docker.io/i386/alpine:3.21.0

ENV KERNEL=virt
ARG EXTRA_PACKAGES=""

RUN apk add --no-cache \
	openrc alpine-base agetty alpine-conf \
	linux-$KERNEL linux-firmware-none \
	${EXTRA_PACKAGES}

RUN sed -i 's/getty 38400 tty1/agetty --autologin root tty1 linux/' /etc/inittab
RUN echo 'ttyS0::respawn:/sbin/agetty --autologin root -s ttyS0 115200 vt100' >> /etc/inittab
RUN echo "root:" | chpasswd
RUN setup-hostname localhost

# Trim optional docs/locales to keep the ext2 image as small as possible.
RUN rm -rf /usr/share/doc /usr/share/man /usr/share/locale/*

# https://wiki.alpinelinux.org/wiki/Alpine_Linux_in_a_chroot#Preparing_init_services
RUN for i in devfs dmesg mdev hwdrivers; do rc-update add $i sysinit; done
RUN for i in hwclock modules sysctl hostname syslog bootmisc; do rc-update add $i boot; done
RUN rc-update add killprocs shutdown

# Rebuild initramfs: include ext2 filesystem module so the ext2 root partition can be mounted.
RUN mkinitfs -F "base virtio 9p ata scsi ext2" $(cat /usr/share/kernel/$KERNEL/kernel.release)
